# Generated by Django 2.2.2 on 2019-06-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190622_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='package_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='application',
            name='package_version_code',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
